package com.amg.digitalitzacio.auth.domain;

public enum BusinessSector {
    PINTOR, ELECTRICISTA, FONTANER, JARDINER, NETEJA,
    FISIOTERAPEUTA, PSICOLEG, NUTRICIONISTA,
    PERRUQUERIA, ESTETICA,
    GESTORIA, ACADEMIA,
    TALLER_MECANIC, VETERINARI, PERRUQUERIA_CANINA,
    RESTAURANTE, INMOBILIARIA
}
