spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:https://amgdl.com,https://www.amgdl.com}

logging:
  level:
    com.amg: INFO
    org.springframework.security: DEBUG
    org.springframework.security.web.access.intercept: TRACE
    org.springframework.security.web.FilterChainProxy: TRACE
